### ISSUE TITLE
Error when loading relatively large amounts of data from SharePoint

### ISSUE THREAD

**Issue by kcjones** [thybag/PHP-SharePoint-Lists-API#102]
I am experiencing the following error when attempting to import a sizable list from SharePoint:

`'DOMDocument::loadXML(): internal error: Huge input lookup in Entity, line: 1' in /vagrant/vendor/thybag/php-sharepoint-lists-api/src/Thybag/SharePointAPI.php:775
`
It appears that setting the LIBXML_PARSEHUGE flag on the loadXML call resolves the issue for me. Would you accept a pull request to make the following change to line 775 in SharePointAPI.php?

From:
`$dom->loadXML($rawXml);`
To:
`$dom->loadXML($rawXml, LIBXML_VERSION >= 20900 ? LIBXML_PARSEHUGE : null);`

Thanks for the great library btw.
- Kevin

**Comment by thybag** [comment]
Have pulled in your changes :)
