### ISSUE TITLE
Error when trying to create a list item

### ISSUE THREAD

**Issue by EDeijl** [thybag/PHP-SharePoint-Lists-API#105]
I can correctly retreive lists and their items, but when I try to add a new item to the list I get the following error log.

I am working with a Sharepoint Online site

````
2016/05/24 14:27:03 [error] 9615#9615: *49 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'Exception' with message 'Error (soap:Client) Server did not recognize the value of HTTP Header SOAPAction: http://schemas.microsoft.com/sharepoint/soap/UpdateListItems", "http://schemas.microsoft.com/sharepoint/soap/UpdateListItems.,more=' in /home/erik/code/Hoppinger/sncu/vendor/thybag/php-sharepoint-lists-api/src/Thybag/SharePointAPI.php:1015
Stack trace:
#0 /home/erik/code/Hoppinger/sncu/vendor/thybag/php-sharepoint-lists-api/src/Thybag/SharePointAPI.php(958): Thybag\SharePointAPI->onError(Object(SoapFault))
#1 /home/erik/code/Hoppinger/sncu/vendor/thybag/php-sharepoint-lists-api/src/Thybag/SharePointAPI.php(509): Thybag\SharePointAPI->modifyList('Meldingen', Array, 'New')
#2 /home/erik/code/Hoppinger/sncu/vendor/thybag/php-sharepoint-lists-api/src/Thybag/SharePointAPI.php(480): Thybag\SharePointAPI->writeMultiple('Meldingen', Array)
````
I'm kinda lost where this comes from, but could it be that it has to do with the following part?
https://github.com/thybag/PHP-SharePoint-Lists-API/blob/develop/src/Thybag/Auth/SharePointOnlineAuth.php#L46

**Comment by eabumere** [comment]
Hello @EDeijl, I have a similar issue to with sharepoint online. Have you managed to get a solution?, If so kindly share.

And any other person that can be of help.

Thanks.

**Comment by thybag** [comment]
Hello,

I don't have access to a copy of SP online to test with, although it sounds like you may be having a similar problem to whats described in http://bluebones.net/2003/07/server-did-not-recognize-http-header-soapaction/

Its possible some of the name spacing may have changed? 

At a guess, i'd say try commenting out https://github.com/thybag/PHP-SharePoint-Lists-API/blob/develop/src/Thybag/Auth/SharePointOnlineAuth.php#L47 and see if that helps at all?

**Comment by eabumere** [comment]
WOOOOOOOOOOOOOOOW!!! For three days I have battled with this. It worked.
I just commented out as directed.
Thanks a million.

**Comment by thybag** [comment]
Have pushed the fix to develop. Thanks for testing that for me :+1:
