### ISSUE TITLE
Using UPDATE affects some columns but not others

### ISSUE THREAD

**Issue by jlisham** [thybag/PHP-SharePoint-Lists-API#112]
when using the UPDATE method, I can update a few columns in a list but not others.  I'm trying to update a lookup column and understand that that may prove problematic, but even the text field columns are hit or miss as to whether they'll be updated.
1. $sp->update('<list>',<ID>, array('last'=>'lastName')) 
2. $sp->update('<list>',<ID>, array('last'=>'lastName','title'=>'firstName')) 

In the case#1, the LAST field will be updated.  In case#2, _neither_ field is updated and there are no errors. EDIT:  I am able to read from this list and all columns are returned

Also - I'm having trouble updating a date/time field?

New to this API so would be most appreciative of your guidance on this.

Thank you for your kind consideration.

**Comment by thybag** [comment]
Hello.

Its odd you don't appear to be getting any errors. At a guess for your second example, SharePoint is pretty strict on casing, so it may be that it wants title to be "Title" (I believe that is what it normally uses by default).

For dates, I'd suggest using the `dateTime` helper if your not already (It should hopefully get it formatted in a way Sharepoint is happy with).

Additionally for the lookup column stuff, sharepoint will be expecting the id of the linked record to be provided. Assuming it has access to the linked list, the magicLookup helper may be able to simplify that a little (although it does require an extra request to sharepoint each time its used)

**Comment by jlisham** [comment]
This turned out to be a case issue and oddly enough, I've found that case can be different for reading vs upload?  and the dateTime helper has proven to be as advertised: helpful :)

Thank you.
