### ISSUE TITLE
Encoding/language support

### ISSUE THREAD

**Issue by gureen-ryuu** [thybag/PHP-SharePoint-Lists-API#115]
When writing data in non-english letters, the resulting info will be saved as ?. For example "القلم" will be written as "?????" in the list.

**Comment by gureen-ryuu** [comment]
Changing $headers[] from `$headers[] = "Content-Type: text/xml; ` to become as follows : `$headers[] = "Content-Type: text/xml; charset=utf-8";` solves the issue.

**Comment by thybag** [comment]
Thanks for figuring out a fix :+1: Will hopefully find some time to pull it in centrally soon.
