### ISSUE TITLE
Sharepoint settings

### ISSUE THREAD

**Issue by Augusto182** [thybag/PHP-SharePoint-Lists-API#118]
Hello.

I think I have a missunderstanding about sharepoint lists. ¿how can I configure a sharepoint list in order to be able to use this library to edit it?

Thank you.

**Comment by thybag** [comment]
Hi @Augusto182 - have just updated the other ticket https://github.com/thybag/PHP-SharePoint-Lists-API/issues/116#issuecomment-267474376

Forgot to ask last time also, but which version of sharepoint are you working against?

**Comment by Augusto182** [comment]
* @author Carl Saggs
 * @version 0.6.4
 * @licence MIT License
 * @source: http://github.com/thybag/PHP-SharePoint-Lists-API

Please, follow the other thread. this should be deleted.

**Comment by thybag** [comment]
Closing as tracking in other ticket

See: #116 (comment)
