### ISSUE TITLE
Get list Error

### ISSUE THREAD

**Issue by tejaskesaria** [thybag/PHP-SharePoint-Lists-API#120]
Hi,

Here is my code:

`<?php
 include "Thybag\SharePointAPI.php";
include "Thybag\Auth\SharePointOnlineAuth.php";
include "Thybag\Auth\SoapClientAuth.php";
include "Thybag\Auth\StreamWrapperHttpAuth.php";
include "Thybag\Service\ListService.php";
include "Thybag\Service\QueryObjectService.php";
    use Thybag\SharePointAPI;
	
    $sp = new SharePointAPI('username.onmicrosoft.com','password','http://localhost/sharepoint/Lists.wsdl','SPONLINE');
    #$sp->getLists();
    $sp->read('<list_name>'); 

    echo "$sp";
?>`

Following is the error I get when I try to run the file:
`Fatal error: Uncaught exception 'Exception' with message 'Error (Receiver) No XML returned,more=' in F:\xampp\htdocs\sharepoint\Thybag\SharePointAPI.php:1016 Stack trace: #0 F:\xampp\htdocs\sharepoint\Thybag\SharePointAPI.php(446): Thybag\SharePointAPI->onError(Object(SoapFault)) #1 F:\xampp\htdocs\sharepoint\Thybag\Service\QueryObjectService.php(210): Thybag\SharePointAPI->read('<list_name>', NULL, Object(Thybag\Service\QueryObjectService), NULL, NULL, NULL) #2 F:\xampp\htdocs\sharepoint\kk.php(13): Thybag\Service\QueryObjectService->get() #3 {main} thrown in F:\xampp\htdocs\sharepoint\Thybag\SharePointAPI.php on line 1016`

**Comment by jonnymaceachern** [comment]
@tejaskesaria How did you resolve this?
