### ISSUE TITLE
write, add or insert is broken

### ISSUE THREAD

**Issue by njovanovich** [thybag/PHP-SharePoint-Lists-API#126]
Like the API, but as the above states, I cant add new values to the list!

**Comment by thybag** [comment]
Hello,

What errors are you getting + which version of SP are you using? 

Sharepoint is very strict over the casing of field names, which can often cause issues when writing back ( the api lowercases everything by default when reading to make it easier to deal with). Assuming it is this reason, you'll likely have got an error complaining about fields not being installed? or something along those lines.

**Comment by Ishadijcks** [comment]
I had the same problem after I changed the name of a column, it only changes the displayName.
You can use `readListMeta` to find out the name of the column. Then use the following line to insert a new value.

`$list->create(array( 'Name'=> $value, 'column'=> value2 ));`

**Comment by njovanovich** [comment]
The names of the fields was the issue
