### ISSUE TITLE
Fatal error: Uncaught Error: Class 'SharePointAPI' not found in file path Thybag API

### ISSUE THREAD

**Issue by Ayaan1010** [thybag/PHP-SharePoint-Lists-API#153]
I'm getting the error 

my code look like this 

require_once('./lib/src/Thybag/SharePointAPI.php');

// 1: connect to SharePoint
$sp = new SharePointAPI('xyz.xyz.com', 'password', './Lists.wsdl','SPONLINE');

// 2: read a list
$listContents = $sp->read('<list_name>'); 

// 3: now you have a 2-D array to work with in PHP
foreach($listContents as $item)
{
    var_dump($item);
}

**Comment by nehagrover027** [comment]
Hi Bhargus,

 Can you please let me know how did you fix this.? I'm facing the same issue.

Thanks
