### ISSUE TITLE
Use of undefined constant SOAP_1_1 - assumed 'SOAP_1_1' (this will throw an Error in a future version of PHP)

### ISSUE THREAD

**Issue by juandiego1990** [thybag/PHP-SharePoint-Lists-API#167]
is there a problem with the PHP version?

I use 7.4.11

**Comment by thybag** [comment]
Hi @juandiego1990, looking at https://www.php.net/manual/en/soap.constants.php it appears the constant still exists at least. 
It's probably worth just double checking the SOAP extension is loaded in your php.ini?

Alternately, if the SOAP version has potentially been dropped (I've no longer got easy access to a SF instance to test) so the lib may be starting to date, you can bump the version on https://github.com/thybag/PHP-SharePoint-Lists-API/blob/develop/src/Thybag/SharePointAPI.php#L115

**Comment by juandiego1990** [comment]
Thanks! It is correct, I needed to add the SOAD extension.

can I consult a file?
