### ISSUE TITLE
Office365 / SharePoint Online support

### ISSUE THREAD

**Issue by nesl247** [thybag/PHP-SharePoint-Lists-API#41]
Please add support for SharePoint Online. It appears that to use SP Online, you need to use Claims based authentication.

I found some info on how to do this here; http://allthatjs.com/2012/03/28/remote-authentication-in-sharepoint-online/

If you need access to a SharePoint Online account to test, please let me know and I will try and get you access.

**Comment by nagharaaj** [comment]
Error: Class 'Thybag\App' not found	
i add  manually  all the files but i have error on  class not found
