### ISSUE TITLE
Fatal error if URL has port number

### ISSUE THREAD

**Issue by ergec** [thybag/PHP-SharePoint-Lists-API#69]
If WSDL url has port number like 

    http://whateverserver:1234/_vti....

Script gives error below

    Fatal error: Uncaught exception 'Exception' with message 'Unable to locate WSDL file. faultcode=0,faultstring=SOAP-ERROR: Parsing WSDL: Couldn't load from

**Comment by comasin** [comment]
I´m getting the same error, any idea how to fix it?

**Comment by thybag** [comment]
Does the entire sharepoint installation have a none default port?

By the sounds of it, it may be PHP's soapclient being a little special (looking at the docs in http://php.net/manual/en/class.soapclient.php#102839 )

I've not tested it, but one work around I've heard is to use the SoapClient proxy options to trick it in to working correctly.

So if your sp installation was `http://whateverserver.com:1234/_vti` you could use:

`$sp = new SharePointAPI('<username>', '<password>', '<path_to_WSDL>', '<auth_method>', array('proxy_host'     => "/whateverserver.com",  'proxy_port'     => 1234));`

If you give it a go, it would be great to hear if it works or not.

P.S. I've only just added the ability to pass options, so you'll need to be using an up to date copy of the devlop branch to try this

**Comment by thybag** [comment]
Given the age of this issue, am closing for now. Happy to reopen if needed :)
