### ISSUE TITLE
How to add Hyperlink text

### ISSUE THREAD

**Issue by vamsip83** [thybag/PHP-SharePoint-Lists-API#70]
What is the command to add hyperlink text? Whenever, I tried to add hyperlinks, it is throwing "One or more field types are not installed properly. Go to the list settings page to delete these fields."  I tried by giving comma between url and text as url, text but it is throwing the above error. I tried reconstructing  the caml but in vain. Please let me the know the solution.

**Comment by thybag** [comment]
Hello,

I'm a little unclear what it is you are attempting to do? Does the code work correctly if you inserting plain text? 

Testing myself, inserting markup (somthing like `$api->write($list, array('my_text_field'=>'I have a <a href="#">link</a>'));` appears to work correctly?

Often "One or more field types are not installed properly.."  error just means you've typoed on of the column names (SP is very fussy about case etc.

**Comment by thybag** [comment]
Given the age of this issue, am closing for now. Happy to reopen if needed :)
