### ISSUE TITLE
MultiChoice field type documentation?

### ISSUE THREAD

**Issue by mrschleig** [thybag/PHP-SharePoint-Lists-API#72]
Love the library.  Any chance of getting some documentation on how $sp->write works with Choice->Checkbox ("MultiChoice" type) fields (maybe just a one-line example)?  I'm tinkering with that now and noticed there wasn't much helpful from Microsoft, either; let me know if that's much more involved than I realize!

**Comment by thybag** [comment]
Honestly, Its not actually anything I've tried. If you figure it out though, any helpful info you can contribute to the readme would be great :)

**Comment by thybag** [comment]
Given the age of this issue, am closing for now. Happy to reopen if needed :)
