### ISSUE TITLE
Issue with SSL v3

### ISSUE THREAD

**Issue by basementjack** [thybag/PHP-SharePoint-Lists-API#74]

**Comment by basementjack** [comment]
I could not get this to connect to our SharePoint Online instance using SSL v3 I think MS may have disabled it at the servers due to the recent poodle vulnerability.

In the file Auth\SharePointOnlineAuth.php, I commented out line 188 in the function authCurl()
//curl_setopt($ch, CURLOPT_SSLVERSION, 3);

That seemed to get me farther, now I'm trying to figure out the right syntax to open a list with a space in the name... (shared documents)

**Comment by basementjack** [comment]
I just noticed that the 'dev' branch has changed from SSL3 to TLS - if you've installed from composer using composer init (like I did :-(, then you'll have issues with SPOnline.)

**Comment by basementjack** [comment]
The correct require statement for your composer.json file if you need TLS in summer 2015 is:
"require": {
        "thybag/php-sharepoint-lists-api": "dev-develop"
    }

I'm sure this will change in the future, for now, it seems accurate

**Comment by thybag** [comment]
Have merged your update in to the trouble shooting section of the readme :)
