### ISSUE TITLE
Character encoding problems

### ISSUE THREAD

**Issue by pavelkucera00** [thybag/PHP-SharePoint-Lists-API#80]
Our script, API and Sharepoint online are using UTF-8 encoding but a Czech special characters are not transferred to Sharepoint via API write function. Does someone have any idea how to solve that?

Thanks a lot

**Comment by pavelkucera00** [comment]
Solved. Minor bug in SharepointOnlineAuth - missing UTF-8 encoding in __doRequest function.

**Comment by pierrejochem** [comment]
Pull Request?

**Comment by thybag** [comment]
Hello,

Would be great to know what you changed in order to fix this. Pull request would be much appreciated :)

**Comment by thybag** [comment]
Given the age of this issue, am closing for now. Happy to reopen if needed :)

**Comment by pierrejochem** [comment]
@pavelkucera00 ?

**Comment by JLauwyck** [comment]
In case someone comes accross this issue. I recently had the same problem (some characters that ended up as ?? instead of è for example).
I fixed my problem by changing line 24 of SharePointOnlineAuth.php.
`$headers[] = "Content-Type: text/xml; charset=UTF-8";`
Thus adding the 
`charset = UTF-8`
