### ISSUE TITLE
Is it possible to read list metadata using given view?

### ISSUE THREAD

**Issue by krystianbuczak** [thybag/PHP-SharePoint-Lists-API#81]
First of all thank you for great job.

My question is simple:
Is it possible to [read](https://github.com/thybag/PHP-SharePoint-Lists-API#list-metadata) list metadata according to specific VIEW? If so what syntax should I use?

**Comment by thybag** [comment]
Hello,

I'm a little unsure what you mean by  "read list metadata according to specific VIEW"? 

Are you looking to get metadata for only fields in a given view?, or is the idea to attempt to read some view specific metadata?

Thanks,
Carl

**Comment by thybag** [comment]
Given the age of this issue, am closing for now. Happy to reopen if needed :)
