### ISSUE TITLE
The security validation for this page is invalid.

### ISSUE THREAD

**Issue by tnsankar** [thybag/PHP-SharePoint-Lists-API#82]
Hi,

I tried to create sharepointlist to store candidate information. I encount the "The security validation for this page is invalid." while attach the file.
I am trying first time in php. I couldn't trace the issue.
This is my code.
$sp->addAttachment('applicant', 18, "files/PID.txt");

How do I resolve this issue? is there any syntax error in the code which I provided.
thanks

**Comment by thybag** [comment]
Hello,

Which version of sharepoint are you running against?

I'm wondering if its possibly related to something like https://support.microsoft.com/en-us/kb/828811 ?

**Comment by tnsankar** [comment]
Hi Carl,



It seems to be security related error similar to the link you provided. But this is when I try to attach the file in to the item.



The suggestion says in the forum to change the global settings to relax the security settings in order to attach the item.



I am trying to work out with Sharepoint Online (office 365). Version not sure. May be online is up to date version.



Thanks for considering my request.



Regards,



T.N.Sankar

**Comment by thybag** [comment]
Hmm, I've just had a test (against SP2013) and the addAttachment method seems fine there.

What permissions does the SP account you're connecting with have to the list (I'm currently using full permissions) ?

It may also be worth pulling the latest copy of develop & giving it another shot with that, just in the unlikely case the authentication fix that just got added in helps

**Comment by tnsankar** [comment]
Hi Carl,



I am using the Global admin permission.



All the syntax for add attachment to the list items is correct. But I stuck somehow. Because you gave example for all SP API action the github.



I will send the screen shot today.



Sankar

**Comment by tnsankar** [comment]
Hi Carl,



Look the error below. The first one is listing items which is success. The second one is the error while attaching file to items.



This is my code. Is there any syntax error? Or probably wrong item Id number 60? Because it is showing 60 the showlist.



require_once('SharePointAPI.php');

require_once('SharePointOnlineAuth.php');



$sp = new SharePointAPI(username', 'password', 'Lists.asmx.xml', 'SPONLINE');

$listContents = $sp->read('applicant');

var_dump($listContents);

$sp->addAttachment('applicant', '60', 'PID.txt');



array (size=1)

  0 =>

    array (size=25)

      'firstname' => string 'sankar' (length=6)

      'lastname' => string 'Natarajan' (length=9)

      'mobnumber' => string '12234546463' (length=11)

      'totalexp' => string '17' (length=2)

      'resumestatus' => string '0' (length=1)

      'fileupload' => string '0' (length=1)

      'emaillink' => string '1.00000000000000' (length=16)

      'jquery' => string 'Selectors, Attach events to dynamic html, Ajax calls, Validations, Setting/Getting attributes, ' (length=95)

      'javascript' => string 'NIL' (length=3)

      'htmlcss' => string 'NIL' (length=3)

     'general' => string 'NIL' (length=3)

      'emailadd' => string 'sankar@stylusinc.com' (length=20)

      '_moderationstatus' => string '0' (length=1)

      '_level' => string '1' (length=1)

      'uniqueid' => string '60;#{DE543B33-A306-4B1B-8ED3-9E827A0A19A7}' (length=42)

      'fsobjtype' => string '60;#0' (length=5)

      'created_x0020_date' => string '60;#2015-10-29 16:59:55' (length=23)

      'modified' => string '2015-11-26 17:33:02' (length=19)

      'fileref' => string '60;#careers/jobs/Lists/applicant/60_.000' (length=40)

      'metainfo' => string '60;#' (length=4)

      'id' => string '60' (length=2)

      'owshiddenversion' => string '2' (length=1)

      'created' => string '2015-10-29 16:59:55' (length=19)

      'fileleafref' => string '60;#60_.000' (length=11)

      'permmask' => string '0x7fffffffffffffff' (length=18)



( ! ) Fatal error: Uncaught exception 'Exception' with message 'Error (soap:Server) Exception of type 'Microsoft.SharePoint.SoapServer.SoapServerException' was thrown.,more=Detailed: The security validation for this page is invalid. Click Back in your Web browser, refresh the page, and try your operation again.' in D:\wamp\www\SP\SharePointAPI.php on line 1015

( ! ) Exception: Error (soap:Server) Exception of type 'Microsoft.SharePoint.SoapServer.SoapServerException' was thrown.,more=Detailed: The security validation for this page is invalid. Click Back in your Web browser, refresh the page, and try your operation again. in D:\wamp\www\SP\SharePointAPI.php on line 1015

Call Stack

#

Time

Memory

Function

Location

1

0.0005

134744

{main}( )

..\list.php:0

2

1.9373

490152

Thybag\SharePointAPI->addAttachment( )

..\list.php:15

3

2.4461

497792

Thybag\SharePointAPI->onError( )

..\SharePointAPI.php:637

**Comment by makarandchavan** [comment]
Having the same issue as stated by you. Unable to attach File. Getting the same error.

**Comment by makarandchavan** [comment]
Hi All,

I manged to crack the solution for the above problem. The issue lies in this file

PHPSharePointListsAPI/src/Thybag/Auth/SharePointOnlineAuth.php on line 22

Just replace $headers = array() with the below code :-

$headers = array('SOAPAction: "' . $action . '"');

Hope that helps if anyone's stuck with it since ages.. :P

**Comment by tnsankar** [comment]
Hi Chavan,



Yup. It is working. You done a good work.. hats off to you.



Sankar

**Comment by thybag** [comment]
Glad to hear its fixed :)

Have added a version of @makarandchavan change to the develop branch, so if you get a chance, would be great to develop branch fix is also working.

Thanks,
Carl
