### ISSUE TITLE
Undefined method SharpointOnlineAuth::GetListCollection()

### ISSUE THREAD

**Issue by pesachzirkind** [thybag/PHP-SharePoint-Lists-API#87]
I think I'm missing something basic here, but when I try to call: $sp->getLists();
I'm getting 'call to undefined method GetListCollection.

Here is the line that is breaking for me in SharepointApi.php
$this->soapClient = new \Thybag\Auth\SharePointOnlineAuth($this->spWsdl, $options);

**Comment by thybag** [comment]
Hello,

I think this is possibly related to https://github.com/thybag/PHP-SharePoint-Lists-API/issues/83 (which meant SP online was unable to authenticate & load the wsdl).

Would you be able to pull the latest version of develop and give it another go? hopefully the issue should be resolved.

**Comment by thybag** [comment]
Given the age of this issue, am closing for now. Happy to reopen if needed :)
