### ISSUE TITLE
RuntimeException: Can't add an item. Unknown Error in SPList->addItem()

### ISSUE THREAD

**Issue by gouravrr** [thybag/PHP-SharePoint-Lists-API#92]
![152](https://cloud.githubusercontent.com/assets/16254220/11869755/0d2ae5aa-a4e8-11e5-8fe1-a461443ebc50.jpg)

Hello,
 I want to add records to sharepoint list, but I stucked in this problem plz help me out.

**Comment by thybag** [comment]
Would you be able to post the code you are attempting to run? (or at least the relevant snippet), without knowing what SPLIst is attempting to do, its hard to guess at what the issue may be.

Thanks :)

**Comment by gouravrr** [comment]
Hello sir,
just send me the code to insert records(hard-coded) to sharepoint list

**Comment by gouravrr** [comment]
that is my code-snippet :

**Comment by gouravrr** [comment]
//insert new item to SharePoint List
function addSPListItem($url,$username,$password){
    $client = new SPOClient($url);
    $client->signIn($username,$password);
    $listTitle = 'crm_contacts';
    $list = $client->getList($listTitle);
    $itemProperties = array('Title' => 'Order Approval', 'Body' => 'Order approval task');
    $taskItem = $list->addItem($itemProperties);
    //print "Task '{$taskItem->Title}' has been created succesfully.\r\n";
    drupal_set_message("Task '{$taskItem->Title}' has been created succesfully.\r\n");
}
//end of insert new item to SharePoint List

I have column i.e firstname in my sharepoint list so send me the code to add name in this field from drupal (just send hard-coded snippet.)

**Comment by thybag** [comment]
Looking at the names of the class's in your example, I think you may actually be using https://github.com/vgrem/phpSPO rather than this library?

Am closing for now, but happy to reopen if I'm wrong.

Thanks,
Carl
