### ISSUE TITLE
Curl verbosity is hard coded to TRUE

### ISSUE THREAD

**Issue by vz28bh** [thybag/PHP-SharePoint-Lists-API#95]
Curl outputs a lot of information that would be nice to turn off.

SoapClientAuth.php, line 112 : curl_setopt($ch, CURLOPT_VERBOSE, TRUE);

Could we default that to false or make it possible to override the curl defaults?  Thanks

**Comment by thybag** [comment]
Hello, thanks for the suggestion, didn't actually notice that was still in there.

The debug stuff should no longer be forced on in the `develop` branch.
https://github.com/thybag/PHP-SharePoint-Lists-API/commit/62148061d15864e51eae53bbb2141c479c3af732
