### ISSUE TITLE
Not working with Office 365 SharePoint?

### ISSUE THREAD

**Issue by horsteisele** [thybag/PHP-SharePoint-Lists-API#98]
Hi, i'm trying to connect with SharePoint in Office 365. I have tried a simple code for testing. The API is loading with no errors but with $sp->read('Adressen');  or $sp->getLists(); there is no response.
Is it possible to use your applicaion with Office 365?

**Comment by thybag** [comment]
I'm not really familiar with office 365's SharePoint so it's hard to say. My hope would be that its fairly similar to SharePoint online, although without a test copy I'm unable to confirm.

Is it returning any error/debug information at all? 

The way the libraries set up, it won't actually attempt to connect until it has a request to make, so any authentication issues won't appear until the call to `$sp->read('Adressen');` or ` $sp->getLists();` etc.

**Comment by horsteisele** [comment]
Hi, i'm sorry. I was blind on both eyes. I've used the wrong auth method. Now it works and i receive my lists. The SharePointOnlineAuth works with Office 365.

**Comment by thybag** [comment]
Ah, good to hear :+1:
