### ISSUE TITLE
Sharepoint lookup fields not being returned in query/read

### ISSUE THREAD

**Issue by mklappen** [thybag/PHP-SharePoint-Lists-API#99]
Was hoping someone could help troubleshoot an issue I'm facing using this plugin. There is a lookup field in our sharepoint list that is not being returned when I query/read the entries.

When I debug the meta info of the sharepoint list I see the lookup column in question `$sp->readListMeta('My List');` which returns the following params
	```(int) 133 => [
		'type' => 'Lookup',
		'displayname' => 'My Lookup Column',
		'required' => 'FALSE',
		'enforceuniquevalues' => 'FALSE',
		'list' => '{5dfe64ab-fb1a-4d70-9cd0-beb5828bb28c}',
		'showfield' => 'Title',
		'unlimitedlengthindocumentlibrary' => 'FALSE',
		'relationshipdeletebehavior' => 'None',
		'id' => '{39475036-db20-4a97-962b-7517770f6018}',
		'sourceid' => '{662334c9-4d09-4e4e-a21d-4a84706932d3}',
		'staticname' => 'My_x0020_Lookup_x0020_Column',
		'name' => 'My_x0020_Lookup_x0020_Column'',
		'colname' => 'int8',
		'rowordinal' => '0',
		'version' => '42',
		'group' => '',
		'mult' => 'FALSE'
	]```

However when I try to query or read the list this column is not present in the return values, even when I can see the value in the front end of sharepoint.
`$sp->query('My List')->where('Status','=','Assigned')->get();`

Was wondering if there are any specific settings that a lookup column must have to be returned? 

Thank you!

**Comment by mklappen** [comment]
Just to add, I have tried using the all_fields() function as well but still no luck on returning the lookup fields. I have confirmed that these fields are also present in the all list views.
`$sp->query('My List')->all_fields()->where('ID','=','2818')->get(); `

**Comment by mklappen** [comment]
knew it was something simple/stupid. It wasn't being returned by all_fields() because it was hidden and needed to pass FALSE

**Comment by thybag** [comment]
Glad to hear yo got it sorted :+1:
